name: Release

on:
  release:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: pwd
        run: pwd
      - name: ls
        run: ls
      - name: env
        run: env
      - name: fail
        run: /bin/false